services:
  - type: web
    name: the-html-archives
    runtime: node
    plan: free
    buildCommand: chmod +x ./build && ./build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
